const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const enterBtn=$('#enterBtn'),hero=$('#hero'),workspace=$('#workspace'),clock=$('#clock'),panelTitle=$('#panelTitle'),integrity=$('#integrity'),pressure=$('#pressure');
let memoryPressure=12,playing=false,audioTimer=null,audioSeconds=0;
function tick(){const d=new Date();clock.textContent=d.toTimeString().slice(0,8)}tick();setInterval(tick,1000);
enterBtn.addEventListener('click',()=>{hero.classList.add('corrupt');setTimeout(()=>{hero.hidden=true;workspace.hidden=false;workspace.classList.add('corrupt');},350)});
const integrityMap={photos:82,chat:61,map:44,audio:29,sealed:3};
$$('.fragment').forEach(btn=>btn.addEventListener('click',()=>{const name=btn.dataset.panel;$$('.fragment').forEach(x=>x.classList.toggle('active',x===btn));$$('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panelContent===name));panelTitle.textContent=`fragment_${btn.querySelector('span').textContent}.${name}`;integrity.textContent=`integrity ${integrityMap[name]}%`;memoryPressure=Math.min(97,memoryPressure+Math.ceil(Math.random()*7));pressure.textContent=`${memoryPressure}%`;workspace.classList.remove('corrupt');void workspace.offsetWidth;workspace.classList.add('corrupt')}));
const chatInput=$('#chatInput'),chatLog=$('#chatLog');$('#sendBtn').addEventListener('click',sendMessage);chatInput.addEventListener('keydown',e=>{if(e.key==='Enter')sendMessage()});
function sendMessage(){const text=chatInput.value.trim();if(!text)return;const p=document.createElement('p');p.innerHTML=`<span>NOW</span>${escapeHtml(text)}`;chatLog.insertBefore(p,chatLog.lastElementChild);chatInput.value='';setTimeout(()=>{const g=chatLog.querySelector('.ghost');g.innerHTML='<span>--:--</span>you should not be able to send messages here.';g.classList.add('corrupt')},700)}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const playBtn=$('#playBtn'),wave=$('#wave'),timecode=$('#timecode');playBtn.addEventListener('click',()=>{playing=!playing;playBtn.textContent=playing?'Ⅱ':'▶';if(playing){wave.animate([{transform:'scaleX(.08)',filter:'brightness(.8)'},{transform:'scaleX(1)',filter:'brightness(1.4)'},{transform:'scaleX(.4)',filter:'brightness(.9)'}],{duration:1300,iterations:Infinity});audioTimer=setInterval(()=>{audioSeconds++;timecode.textContent=`00:${String(audioSeconds%60).padStart(2,'0')}`},1000)}else{clearInterval(audioTimer);wave.getAnimations().forEach(a=>a.cancel())}});
const terminal=$('#terminal');$('#openSealed').addEventListener('click',()=>{const lines=['> reconstruct fragment 05','> checksum mismatch','> owner: [REDACTED]','> last modified: tomorrow','> WARNING: archive contains observer state','> observer state: ACTIVE','> hello.'];terminal.textContent='';let i=0;const timer=setInterval(()=>{terminal.textContent+=lines[i++]+'\n';if(i===lines.length){clearInterval(timer);document.body.classList.add('corrupt');setTimeout(()=>document.body.classList.remove('corrupt'),700)}},260)});
$('#mapCard').addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;e.currentTarget.style.transform=`perspective(900px) rotateX(${y*-2.5}deg) rotateY(${x*3}deg)`});$('#mapCard').addEventListener('pointerleave',e=>e.currentTarget.style.transform='');